spring:
  config:
    activate:
      on-profile: "prod"

build:
  version: "1.0"

accounts:
  message: "Welcome to EazyBank loans * PRODUCTION * related APIs"
  contactDetails:
    name: "John Cleese - CEO"
    email: "john.cleese@eazybank.com"
  onCallSupport:
    - (555) 555-54321
    - (555) 555-98765