server:
  port: 8090
spring:
  application:
    name: "loans"
  datasource:
    url: jdbc:mysql://localhost:3308/loansdb
    username: root
    password: 'root'
  jpa:
    show-sql: true
  sql:
    init:
      mode: always
  profiles:
    active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"
