spring:
  config:
    activate:
      on-profile: "qa"

build:
  version: "2.0"

accounts:
  message: "Welcome to EazyBank loans related APIs"
  contactDetails:
    name: "John Doese - QA Lead"
    email: "john.doese@eazybank.com"
  onCallSupport:
    - (555) 555-12345
    - (555) 555-56789